# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e24d6051089fa8fdd9f3e3f262454357c398d91cfb4b7158e71ee8d2f8ec640af381b5a56d0ebf501a84ddca5b6c525266d16356f11c618df50134c90c9a275

test:
  secret_key_base: 9104098265ad364eb37cf22f1f504afe24e6e4263788f809fea04cfd4ba8eab743af4dd00c38bf32eff9731cc53fcff39a528d5a8aceb104f5758bf7f7c30edb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
